## static ##
# routeur_gloukas-1 configuration #

ip link add br0 type bridge
ip link set dev br0 up
ip addr add 193.172.1.1/24 dev eth0
ip link add name vxlan10 type vxlan id 10 dev eth0 remote 193.172.1.2 local 193.172.1.1 dstport 4789
ip addr add 193.173.1.1/24 dev vxlan10
brctl addif br0 eth1
brctl addif br0 vxlan10
ip link set dev vxlan10 up

# routeur_gloukas-2 configuration #

ip link add br0 type bridge
ip link set dev br0 up
ip addr add 193.172.1.2/24 dev eth0
ip link add name vxlan10 type vxlan id 10 dev eth0 remote 193.172.1.1 local 193.172.1.2 dstport 4789
ip addr add 193.173.1.2/24 dev vxlan10
brctl addif br0 eth1
brctl addif br0 vxlan10
ip link set dev vxlan10 up

# host_gloukas-1 configuration #

ip addr add 156.20.1.1/24 dev eth1
ip link set dev eth1 up

# host_gloukas-2 configuration #

ip addr add 156.20.1.2/24 dev eth1
ip link set dev eth1 up

## dynamic multicast ##
# routeur_gloukas-1 configuration #

ip link add br0 type bridge
ip link set dev br0 up
ip addr add 193.172.1.1/24 dev eth0
ip link add name vxlan10 type vxlan id 10 dev eth0 group 239.1.1.1 dstport 4789
ip addr add 193.173.1.1/24 dev vxlan10
brctl addif br0 eth1
brctl addif br0 vxlan10
ip link set dev vxlan10 up

# routeur_gloukas-2 configuration #

ip link add br0 type bridge
ip link set dev br0 up
ip addr add 193.172.1.2/24 dev eth0
ip link add name vxlan10 type vxlan id 10 dev eth0 group 239.1.1.1 dstport 4789
ip addr add 193.173.1.2/24 dev vxlan10
brctl addif br0 eth1
brctl addif br0 vxlan10
ip link set dev vxlan10 up